### ISSUE TITLE
Memory leak in `recursive`

### ISSUE THREAD

**Issue by ekzhang** [zesterer/chumsky#36] opened 2021-11-30 01:42 UTC
Hi again, and thanks for the great crate! I've had a lot of fun using it so far.

### Issue

The `recursive` implementation in this crate leaks memory if it is used in the intended way, due to an `Rc` reference cycle. Here is the relevant excerpt from [`recursive.rs`](https://github.com/zesterer/chumsky/blob/82bfe16a894585cee802795b47d94ada561a2fdb/src/recursive.rs).

```rust
/// A parser that can be defined in terms of itself by separating its [declaration](Recursive::declare) from its
/// [definition](Recursive::define).
///
/// Prefer to use [`recursive()`], which exists as a convenient wrapper around both operations, if possible.
pub struct Recursive<'a, I, O, E: Error<I>>(Rc<OnceCell<Box<dyn Parser<I, O, Error = E> + 'a>>>);

impl<'a, I: Clone, O, E: Error<I>> Recursive<'a, I, O, E> {
    /// Declare the existence of a recursive parser, allowing it to be used to construct parser combinators before
    /// being fulled defined.
    ///
    /// <abridged>
    pub fn declare() -> Self {
        Recursive(Rc::new(OnceCell::new()))
    }

    /// Defines the parser after declaring it, allowing it to be used for parsing.
    pub fn define<P: Parser<I, O, Error = E> + 'a>(&mut self, parser: P) {
        self.0
            .set(Box::new(parser))
            .unwrap_or_else(|_| panic!("Parser defined more than once"));
    }
}
```

Even after a recursive parser is dropped, if it is self-referential, the underlying memory will not be freed. For example, the `json` example has this issue. Running the following file with `cargo +nightly miri run` will panic with a memory leak detected:

```rust
use std::collections::HashMap;

use chumsky::prelude::*;

#[derive(Clone, Debug)]
enum Json {
    Invalid,
    Null,
    Bool(bool),
    Str(String),
    Num(f64),
    Array(Vec<Json>),
    Object(HashMap<String, Json>),
}

fn parser() -> impl Parser<char, Json, Error = Simple<char>> {
    recursive(|value| {
        let frac = just('.').chain(text::digits(10));

        let exp = just('e')
            .or(just('E'))
            .ignore_then(just('+').or(just('-')).or_not())
            .chain(text::digits(10));

        let number = just('-')
            .or_not()
            .chain(text::int(10))
            .chain(frac.or_not().flatten())
            .chain::<char, _, _>(exp.or_not().flatten())
            .collect::<String>()
            .map(|s| s.parse().unwrap())
            .labelled("number");

        let escape = just('\\').ignore_then(
            just('\\')
                .or(just('/'))
                .or(just('"'))
                .or(just('b').to('\x08'))
                .or(just('f').to('\x0C'))
                .or(just('n').to('\n'))
                .or(just('r').to('\r'))
                .or(just('t').to('\t')),
        );

        let string = just('"')
            .ignore_then(filter(|c| *c != '\\' && *c != '"').or(escape).repeated())
            .then_ignore(just('"'))
            .collect::<String>()
            .labelled("string");

        let array = value
            .clone()
            .chain(just(',').ignore_then(value.clone()).repeated())
            .or_not()
            .flatten()
            .delimited_by('[', ']')
            .map(Json::Array)
            .labelled("array");

        let member = string.clone().then_ignore(just(':').padded()).then(value);
        let object = member
            .clone()
            .chain(just(',').padded().ignore_then(member).repeated())
            .or_not()
            .flatten()
            .padded()
            .delimited_by('{', '}')
            .collect::<HashMap<String, Json>>()
            .map(Json::Object)
            .labelled("object");

        seq("null".chars())
            .to(Json::Null)
            .labelled("null")
            .or(seq("true".chars()).to(Json::Bool(true)).labelled("true"))
            .or(seq("false".chars()).to(Json::Bool(false)).labelled("false"))
            .or(number.map(Json::Num))
            .or(string.map(Json::Str))
            .or(array)
            .or(object)
            .recover_with(nested_delimiters('{', '}', [('[', ']')], |_| Json::Invalid))
            .recover_with(nested_delimiters('[', ']', [('{', '}')], |_| Json::Invalid))
            .recover_with(skip_then_retry_until(['}', ']']))
            .padded()
    })
    .then_ignore(end().recover_with(skip_then_retry_until([])))
}

fn main() {
    let _parser = parser();
}
```

Here is a more minimal example of the memory leak:

```rust
use chumsky::prelude::*;

fn main() {
    let parser = recursive(|f| just::<char, Simple<_>>('x').or(f.delimited_by('(', ')')));
    parser.parse("((x))").unwrap();
}
```

And the output from Miri:

```
The following memory was leaked: alloc1125 (Rust heap, size: 40, align: 8) {
    0x00 │ 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 │ ................
    0x10 │ 00 00 00 00 00 00 00 00 ╾0x26658[a1232]<2580>─╼ │ ........╾──────╼
    0x20 │ ╾0x268b0[a1265]<2571>─╼                         │ ╾──────╼
}
alloc1232 (Rust heap, size: 24, align: 8) {
    0x00 │ ╾0x25d08[a1125]<untagged> (8 ptr bytes)╼ 28 00 00 00 29 00 00 00 │ ╾──────╼(...)...
    0x10 │ 78 00 00 00 __ __ __ __                         │ x...░░░░
}
alloc1265 (global (static or const), size: 40, align: 8) {
    0x00 │ ╾0x268e0[a1262]<2572>─╼ 18 00 00 00 00 00 00 00 │ ╾──────╼........
    0x10 │ 08 00 00 00 00 00 00 00 ╾0x268ee[a1263]<2573>─╼ │ ........╾──────╼
    0x20 │ ╾0x268fe[a1264]<2574>─╼                         │ ╾──────╼
}
alloc1262 (fn: std::ptr::drop_in_place::<chumsky::combinator::Or<chumsky::primitive::Just<char, chumsky::error::Simple<char>>, chumsky::combinator::DelimitedBy<chumsky::recursive::Recursive<char, char, chumsky::error::Simple<char>>, char>>> - shim(Some(chumsky::combinator::Or<chumsky::primitive::Just<char, chumsky::error::Simple<char>>, chumsky::combinator::DelimitedBy<chumsky::recursive::Recursive<char, char, chumsky::error::Simple<char>>, char>>)))
alloc1263 (fn: <chumsky::combinator::Or<chumsky::primitive::Just<char, chumsky::error::Simple<char>>, chumsky::combinator::DelimitedBy<chumsky::recursive::Recursive<char, char, chumsky::error::Simple<char>>, char>> as chumsky::Parser<char, char>>::parse_inner_verbose)
alloc1264 (fn: <chumsky::combinator::Or<chumsky::primitive::Just<char, chumsky::error::Simple<char>>, chumsky::combinator::DelimitedBy<chumsky::recursive::Recursive<char, char, chumsky::error::Simple<char>>, char>> as chumsky::Parser<char, char>>::parse_inner_silent)

error: the evaluated program leaked memory

note: pass `-Zmiri-ignore-leaks` to disable this check

error: aborting due to previous error
```

I'm not sure what the best way to fix this is, is it possible to demote some of the `Rc`s to `Weak` pointers?

**Comment by zesterer** [comment] 2021-11-30 15:53
Ah, this is a good point! I should probably switch to using `Weak` pointers instead. I'll try to implement this by the end of the week. Thanks for opening the issue!

**Comment by zesterer** [comment] 2021-11-30 16:13
I've fixed this in 1017d4, although I'm not yet completely satisfied with the implementation.

**Comment by ekzhang** [comment] 2021-11-30 20:32
Thanks! The example doesn't leak memory anymore, I checked with Miri. :)

> ... although I'm not yet completely satisfied with the implementation.

Is the reason why because of this excerpt?

```rust
impl<'a, I: Clone, O, E: Error<I>> Recursive<'a, I, O, E> {
    fn cell(&self) -> Rc<OnceCell<Box<dyn Parser<I, O, Error = E> + 'a>>> {
        match &self.0 {
            RecursiveInner::Owned(x) => x.clone(),
            RecursiveInner::Unowned(x) => x
                .upgrade()
                .expect("Recursive parser used before being defined"),
        }
    }
```

The following code triggers that error:

```rust
use chumsky::prelude::*;

fn main() {
    let parser = recursive(|f| just::<char, Simple<_>>('x').or(f.delimited_by('(', ')')));
    let parser2 = parser.clone();
    drop(parser);
    parser2.parse("((x))").unwrap();
}
```

This panics with "Recursive parser used before being defined" - no idea how to avoid the issue from a library perspective, just letting you know!

**Comment by zesterer** [comment] 2021-12-01 09:37
I've made another attempt at fixing this in 870eca3. Now, any clone of the outer parser is be owning and any clone of the inner parser will be non-owning.

**Comment by IWANABETHATGUY** [comment] 2022-02-16 17:24
It seems this problem has been fixed by https://github.com/zesterer/chumsky/commit/870eca3a388a097050d83adc2c77df551fe1b7da, and I can't reproduce after run command 
`cargo +nightly miri run`

**Closed** 2022-02-16 18:44 UTC
