### ISSUE TITLE
Examples for using Parser::debug()

### ISSUE THREAD

**Issue by natemartinsf** [zesterer/chumsky#15] opened 2021-11-02 03:27 UTC
Can you share any examples for using the debug() parser? It requires a single argument, x<t>, but the documentation doesn't specify what this should be. 

I've tried wrapping another parser in debug(), and tried adding it as the final combinator, but neither would compile.

**Comment by zesterer** [comment] 2021-11-02 08:25
The debugging features of Chumsky are still quite early in development and I'm still doing some thinking about how I want to proceed with them.

>  It requires a single argument, x, but the documentation doesn't specify what this should be.

It can be literally anything that you want to use to label a particular parser in the debugging output. I tend to use things like `"expression"`, `"pattern"`, `"atom"`, etc. depending on the context. It doesn't mean anything to the debugger, it just gets used to identify it in the output.

**Comment by natemartinsf** [comment] 2021-11-03 02:07
Ah, thanks! Would it be worth me doing a PR to add a sentence to the documentation, or is this likely to change too much as you add debugging features?

**Comment by zesterer** [comment] 2021-11-03 08:19
Some documentation would be useful, yes! I'll also open an issue regard parser debugging to help flesh out some ideas about how it should work.

**Comment by zesterer** [comment] 2021-11-03 08:22
(The issue is [here](#19)

**Comment by zesterer** [comment] 2023-02-20 22:29
Closing in favour of #19.

**Closed by zesterer** 2023-02-20 22:29 UTC
Labels: documentation, help wanted
